/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 93
#define YY_END_OF_BUFFER 94
static yyconst short int yy_accept[228] =
    {   0,
        0,    0,   94,   92,   91,   90,   92,   92,   89,   70,
       65,   92,   58,   59,   76,   69,   55,   68,   64,   78,
       81,   81,   56,   71,   57,   72,   66,   80,   80,   35,
       80,   80,   80,   80,   60,   61,   73,   75,   80,   80,
       80,   80,   80,   80,   80,   80,   36,   80,   80,   80,
       80,   80,   80,   80,   80,   62,   74,   63,   67,   91,
       54,    0,   87,    0,   89,   45,   46,    0,   87,    0,
       77,   42,   40,   41,    0,   84,   79,   44,   84,   82,
        0,    0,   86,    0,   81,   50,   51,   53,   52,   49,
       80,   80,   80,    0,    0,   80,   80,   47,   80,    5,

       80,   80,   80,   80,   80,   80,   80,   80,   80,   80,
       19,   80,   21,   22,   80,   80,   25,   80,   80,   80,
       80,   80,   80,   80,   80,   48,   87,    0,    0,   43,
       37,   84,    0,   85,   83,   39,   38,   80,   80,    0,
       80,    4,   80,   80,   80,   80,   10,   11,   80,   80,
       80,   80,   80,   16,   80,   80,   80,   80,   24,   80,
       80,   80,   80,   29,   80,   80,   80,    0,    0,    0,
        0,    0,    0,   80,    2,    3,   80,   80,   80,   80,
       12,   13,   80,   34,   80,   17,   80,   80,   80,   26,
       80,   80,   80,   80,   31,   80,    0,    0,    1,   80,

        7,    8,   80,   80,   80,   80,   80,   80,   33,   27,
       80,   30,   32,   88,   88,    6,   80,   14,   80,   18,
       20,   23,   28,   80,   15,    9,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    1,    7,    8,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   19,
       19,   19,   19,   19,   19,   20,   20,   21,    1,   22,
       23,   24,    1,   25,   26,   26,   26,   26,   27,   28,
       29,   29,   29,   30,   29,   31,   29,   32,   29,   29,
       29,   33,   29,   34,   35,   29,   29,   36,   29,   29,
       37,   38,   39,   40,   29,   41,   42,   43,   44,   45,

       46,   47,   48,   49,   50,   51,   52,   53,   54,   55,
       56,   57,   29,   58,   59,   60,   61,   29,   62,   63,
       64,   29,   65,   66,   67,   68,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[69] =
    {   0,
        1,    1,    2,    1,    3,    1,    1,    1,    4,    1,
        1,    1,    1,    1,    1,    1,    1,    5,    5,    5,
        1,    1,    1,    1,    1,    5,    5,    5,    6,    6,
        6,    6,    6,    6,    6,    6,    1,    1,    1,    1,
        1,    5,    5,    5,    5,    5,    5,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    1,    1,    1,    1
    } ;

static yyconst short int yy_base[235] =
    {   0,
        0,    0,  363,  364,   67,   69,  339,   68,    0,  338,
      337,   65,  364,  364,   63,  336,  364,  335,   60,   60,
       69,   82,  364,   59,  334,   67,  364,    0,  314,    0,
      299,   88,  296,  102,  364,  364,  330,  364,   49,  294,
       39,  305,   31,   60,  297,   67,  307,  292,  289,   71,
      122,  288,  114,   75,  295,  364,  321,  364,  364,  134,
      364,  112,  338,  333,    0,  364,  364,  121,  332,  335,
      316,  364,  364,  364,  322,  124,  364,  364,  147,  160,
      183,  143,  364,    0,  189,  314,  364,  364,  364,  313,
        0,  282,  279,  328,  131,  271,  129,  364,  286,  271,

      283,  286,  272,   92,   96,  127,  271,  267,  268,  267,
        0,  265,    0,    0,  267,  260,    0,  260,  268,  267,
      256,  251,  264,  253,  266,  364,  364,  143,  144,  364,
      364,  203,  165,  206,    0,  364,  364,  252,  264,  304,
      262,    0,  261,  264,  246,  244,    0,    0,  256,  256,
      255,  256,  257,    0,  244,  254,  240,  252,    0,  235,
      238,  233,  230,    0,  237,  223,  218,  189,  190,  262,
      148,  179,  258,  213,    0,    0,  198,  203,  194,  202,
        0,    0,  194,    0,  197,    0,  206,  189,  201,    0,
      184,  197,  184,  195,    0,  194,  199,  180,    0,  178,

        0,    0,  177,  171,  162,  161,  140,  155,    0,    0,
      141,    0,    0,  207,  182,    0,  131,    0,   88,    0,
        0,    0,    0,  103,    0,    0,  364,  257,  263,  269,
      271,  136,  277,  283
    } ;

static yyconst short int yy_def[235] =
    {   0,
      227,    1,  227,  227,  227,  227,  227,  228,  229,  227,
      227,  230,  227,  227,  227,  227,  227,  227,  227,  227,
      227,  227,  227,  227,  227,  227,  227,  231,  231,  231,
      231,  231,  231,  231,  227,  227,  227,  227,  231,  231,
      231,  231,  231,  231,  231,  231,  231,  231,  231,  231,
      231,  231,  231,  231,  231,  227,  227,  227,  227,  227,
      227,  228,  227,  228,  229,  227,  227,  230,  227,  230,
      227,  227,  227,  227,  227,  227,  227,  227,  227,  227,
      227,  227,  227,  232,  227,  227,  227,  227,  227,  227,
      231,  231,  231,  227,  230,  231,  231,  227,  231,  231,

      231,  231,  231,  231,  231,  231,  231,  231,  231,  231,
      231,  231,  231,  231,  231,  231,  231,  231,  231,  231,
      231,  231,  231,  231,  231,  227,  227,  233,  234,  227,
      227,  227,  227,  227,  232,  227,  227,  231,  231,  227,
      231,  231,  231,  231,  231,  231,  231,  231,  231,  231,
      231,  231,  231,  231,  231,  231,  231,  231,  231,  231,
      231,  231,  231,  231,  231,  231,  231,  233,  233,  233,
      234,  234,  234,  231,  231,  231,  231,  231,  231,  231,
      231,  231,  231,  231,  231,  231,  231,  231,  231,  231,
      231,  231,  231,  231,  231,  231,  233,  234,  231,  231,

      231,  231,  231,  231,  231,  231,  231,  231,  231,  231,
      231,  231,  231,  233,  234,  231,  231,  231,  231,  231,
      231,  231,  231,  231,  231,  231,    0,  227,  227,  227,
      227,  227,  227,  227
    } ;

static yyconst short int yy_nxt[433] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   22,
       23,   24,   25,   26,   27,   28,   28,   29,   28,   28,
       30,   31,   32,   33,   34,   28,   35,    4,   36,   37,
       38,   39,   40,   41,   42,   43,   44,   45,   28,   46,
       28,   28,   47,   28,   48,   49,   50,   51,   28,   52,
       53,   54,   28,   55,   56,   57,   58,   59,   60,   60,
       60,   60,   63,   69,   71,   75,   77,   76,   76,   76,
       86,   87,   78,  105,   79,   72,   80,   80,   81,   89,
       90,  102,   94,  106,  103,   82,   95,   79,   83,   85,

       85,   85,   70,   99,   84,   64,   94,  100,   82,  107,
       95,   83,  118,  111,   82,  108,  127,  109,   94,   83,
      112,  113,   95,  123,  124,  114,   94,   82,  119,  127,
       95,   84,   83,   94,   97,   60,   60,   95,  147,   69,
      135,   76,   76,   76,  148,  149,   97,  169,  226,   64,
       82,  225,  172,   83,  150,  133,  172,  133,   70,   97,
      134,  134,  134,  120,  132,  132,  132,  121,   70,   82,
      151,   97,  152,   82,   83,   79,   83,   80,   80,   81,
      170,  173,  134,  134,  134,  173,   82,  198,  215,   83,
      215,  224,   82,  169,  197,  223,  222,   83,   79,  221,

       81,   81,   81,  214,   79,   82,   85,   85,   85,   82,
       83,  214,   83,  220,  219,   82,  173,  173,   83,  173,
      132,  132,  132,  134,  134,  134,  170,  170,   82,   82,
      218,  217,   83,   83,   82,   83,  170,  216,  213,   83,
      212,  211,  210,  209,  170,  208,  207,  206,   82,  205,
      204,  203,  202,   83,  201,  200,   83,   62,  199,   62,
      227,   62,   62,   65,  227,   65,   65,   65,   65,   68,
      196,  195,   68,   68,   68,   91,   91,  168,  168,  168,
      168,  168,  168,  171,  171,  171,  171,  171,  171,  194,
      193,  192,  191,  190,  189,  188,  187,  186,  185,  184,

      183,  182,  181,  180,  179,  178,  177,  176,  128,  175,
      174,  167,  166,  165,  164,  163,  162,  161,  160,  159,
      158,  157,  156,  155,  154,  153,  146,  145,  144,  143,
      142,  141,  140,  139,  138,  137,  136,  131,  130,   68,
      129,   62,  128,  126,  125,  122,  117,  116,  115,  110,
      104,  101,   98,   96,   93,   92,   88,   74,   73,   67,
       66,   61,  227,    3,  227,  227,  227,  227,  227,  227,
      227,  227,  227,  227,  227,  227,  227,  227,  227,  227,
      227,  227,  227,  227,  227,  227,  227,  227,  227,  227,
      227,  227,  227,  227,  227,  227,  227,  227,  227,  227,

      227,  227,  227,  227,  227,  227,  227,  227,  227,  227,
      227,  227,  227,  227,  227,  227,  227,  227,  227,  227,
      227,  227,  227,  227,  227,  227,  227,  227,  227,  227,
      227,  227
    } ;

static yyconst short int yy_chk[433] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    5,    5,
        6,    6,    8,   12,   15,   19,   20,   19,   19,   19,
       24,   24,   20,   43,   21,   15,   21,   21,   21,   26,
       26,   41,   32,   43,   41,   21,   32,   22,   21,   22,

       22,   22,   12,   39,   21,    8,   34,   39,   22,   44,
       34,   22,   50,   46,   21,   44,   62,   44,   53,   21,
       46,   46,   53,   54,   54,   46,   51,   22,   50,   68,
       51,   21,   22,   97,   34,   60,   60,   97,  104,   95,
      232,   76,   76,   76,  104,  105,   53,  128,  224,   62,
       76,  219,  129,   76,  105,   82,  171,   82,   68,   34,
       82,   82,   82,   51,   79,   79,   79,   51,   95,   76,
      106,   53,  106,   79,   76,   80,   79,   80,   80,   80,
      128,  129,  133,  133,  133,  171,   80,  172,  198,   80,
      215,  217,   79,  168,  169,  211,  208,   79,   81,  207,

       81,   81,   81,  197,   85,   80,   85,   85,   85,   81,
       80,  214,   81,  206,  205,   85,  172,  198,   85,  215,
      132,  132,  132,  134,  134,  134,  168,  169,   81,  132,
      204,  203,  132,   81,   85,  134,  197,  200,  196,   85,
      194,  193,  192,  191,  214,  189,  188,  187,  132,  185,
      183,  180,  179,  132,  178,  177,  134,  228,  174,  228,
      173,  228,  228,  229,  170,  229,  229,  229,  229,  230,
      167,  166,  230,  230,  230,  231,  231,  233,  233,  233,
      233,  233,  233,  234,  234,  234,  234,  234,  234,  165,
      163,  162,  161,  160,  158,  157,  156,  155,  153,  152,

      151,  150,  149,  146,  145,  144,  143,  141,  140,  139,
      138,  125,  124,  123,  122,  121,  120,  119,  118,  116,
      115,  112,  110,  109,  108,  107,  103,  102,  101,  100,
       99,   96,   94,   93,   92,   90,   86,   75,   71,   70,
       69,   64,   63,   57,   55,   52,   49,   48,   47,   45,
       42,   40,   37,   33,   31,   29,   25,   18,   16,   11,
       10,    7,    3,  227,  227,  227,  227,  227,  227,  227,
      227,  227,  227,  227,  227,  227,  227,  227,  227,  227,
      227,  227,  227,  227,  227,  227,  227,  227,  227,  227,
      227,  227,  227,  227,  227,  227,  227,  227,  227,  227,

      227,  227,  227,  227,  227,  227,  227,  227,  227,  227,
      227,  227,  227,  227,  227,  227,  227,  227,  227,  227,
      227,  227,  227,  227,  227,  227,  227,  227,  227,  227,
      227,  227
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "D:\\Testing\\Repos\\PythonGrammar\\PythonGrammar\\python_lexic.l"
#define INITIAL 0
#line 2 "D:\\Testing\\Repos\\PythonGrammar\\PythonGrammar\\python_lexic.l"
	#pragma warning(disable: 4013)
	#pragma warning(disable: 4996)

	#include <stdio.h>
	#include <stdlib.h>
	
	#include "y.tab.h"

	unsigned int line_number = 1;
#line 547 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 40 "D:\\Testing\\Repos\\PythonGrammar\\PythonGrammar\\python_lexic.l"


#line 701 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 228 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 364 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 42 "D:\\Testing\\Repos\\PythonGrammar\\PythonGrammar\\python_lexic.l"
{ return FALSE; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 43 "D:\\Testing\\Repos\\PythonGrammar\\PythonGrammar\\python_lexic.l"
{ return NONE; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 44 "D:\\Testing\\Repos\\PythonGrammar\\PythonGrammar\\python_lexic.l"
{ return TRUE; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 45 "D:\\Testing\\Repos\\PythonGrammar\\PythonGrammar\\python_lexic.l"
{ return AND; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 46 "D:\\Testing\\Repos\\PythonGrammar\\PythonGrammar\\python_lexic.l"
{ return AS; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 47 "D:\\Testing\\Repos\\PythonGrammar\\PythonGrammar\\python_lexic.l"
{ return ASSERT; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 48 "D:\\Testing\\Repos\\PythonGrammar\\PythonGrammar\\python_lexic.l"
{ return BREAK; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 49 "D:\\Testing\\Repos\\PythonGrammar\\PythonGrammar\\python_lexic.l"
{ return CLASS; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 50 "D:\\Testing\\Repos\\PythonGrammar\\PythonGrammar\\python_lexic.l"
{ return CONTINUE; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 51 "D:\\Testing\\Repos\\PythonGrammar\\PythonGrammar\\python_lexic.l"
{ return DEF; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 52 "D:\\Testing\\Repos\\PythonGrammar\\PythonGrammar\\python_lexic.l"
{ return DEL; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 53 "D:\\Testing\\Repos\\PythonGrammar\\PythonGrammar\\python_lexic.l"
{ return ELIF; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 54 "D:\\Testing\\Repos\\PythonGrammar\\PythonGrammar\\python_lexic.l"
{ return ELSE; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 55 "D:\\Testing\\Repos\\PythonGrammar\\PythonGrammar\\python_lexic.l"
{ return EXCEPT; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 56 "D:\\Testing\\Repos\\PythonGrammar\\PythonGrammar\\python_lexic.l"
{ return FINALLY; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 57 "D:\\Testing\\Repos\\PythonGrammar\\PythonGrammar\\python_lexic.l"
{ return FOR; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 58 "D:\\Testing\\Repos\\PythonGrammar\\PythonGrammar\\python_lexic.l"
{ return FROM; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 59 "D:\\Testing\\Repos\\PythonGrammar\\PythonGrammar\\python_lexic.l"
{ return GLOBAL; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 60 "D:\\Testing\\Repos\\PythonGrammar\\PythonGrammar\\python_lexic.l"
{ return IF; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 61 "D:\\Testing\\Repos\\PythonGrammar\\PythonGrammar\\python_lexic.l"
{ return IMPORT; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 62 "D:\\Testing\\Repos\\PythonGrammar\\PythonGrammar\\python_lexic.l"
{ return IN; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 63 "D:\\Testing\\Repos\\PythonGrammar\\PythonGrammar\\python_lexic.l"
{ return IS; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 64 "D:\\Testing\\Repos\\PythonGrammar\\PythonGrammar\\python_lexic.l"
{ return LAMBDA; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 65 "D:\\Testing\\Repos\\PythonGrammar\\PythonGrammar\\python_lexic.l"
{ return NOT; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 66 "D:\\Testing\\Repos\\PythonGrammar\\PythonGrammar\\python_lexic.l"
{ return OR; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 67 "D:\\Testing\\Repos\\PythonGrammar\\PythonGrammar\\python_lexic.l"
{ return PASS; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 68 "D:\\Testing\\Repos\\PythonGrammar\\PythonGrammar\\python_lexic.l"
{ return RAISE; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 69 "D:\\Testing\\Repos\\PythonGrammar\\PythonGrammar\\python_lexic.l"
{ return RETURN; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 70 "D:\\Testing\\Repos\\PythonGrammar\\PythonGrammar\\python_lexic.l"
{ return TRY; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 71 "D:\\Testing\\Repos\\PythonGrammar\\PythonGrammar\\python_lexic.l"
{ return WHILE; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 72 "D:\\Testing\\Repos\\PythonGrammar\\PythonGrammar\\python_lexic.l"
{ return WITH; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 73 "D:\\Testing\\Repos\\PythonGrammar\\PythonGrammar\\python_lexic.l"
{ return YIELD; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 75 "D:\\Testing\\Repos\\PythonGrammar\\PythonGrammar\\python_lexic.l"
{ return PRINT; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 76 "D:\\Testing\\Repos\\PythonGrammar\\PythonGrammar\\python_lexic.l"
{ return EXEC; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 78 "D:\\Testing\\Repos\\PythonGrammar\\PythonGrammar\\python_lexic.l"
{ return 'L'; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 79 "D:\\Testing\\Repos\\PythonGrammar\\PythonGrammar\\python_lexic.l"
{ return 'l'; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 81 "D:\\Testing\\Repos\\PythonGrammar\\PythonGrammar\\python_lexic.l"
{ return ELLIPSIS; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 82 "D:\\Testing\\Repos\\PythonGrammar\\PythonGrammar\\python_lexic.l"
{ return RIGHT_ASSIGN; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 83 "D:\\Testing\\Repos\\PythonGrammar\\PythonGrammar\\python_lexic.l"
{ return LEFT_ASSIGN; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 84 "D:\\Testing\\Repos\\PythonGrammar\\PythonGrammar\\python_lexic.l"
{ return ADD_ASSIGN; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 85 "D:\\Testing\\Repos\\PythonGrammar\\PythonGrammar\\python_lexic.l"
{ return SUB_ASSIGN; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 86 "D:\\Testing\\Repos\\PythonGrammar\\PythonGrammar\\python_lexic.l"
{ return MUL_ASSIGN; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 87 "D:\\Testing\\Repos\\PythonGrammar\\PythonGrammar\\python_lexic.l"
{ return POW_ASSIGN; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 88 "D:\\Testing\\Repos\\PythonGrammar\\PythonGrammar\\python_lexic.l"
{ return DIV_ASSIGN; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 89 "D:\\Testing\\Repos\\PythonGrammar\\PythonGrammar\\python_lexic.l"
{ return MOD_ASSIGN; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 90 "D:\\Testing\\Repos\\PythonGrammar\\PythonGrammar\\python_lexic.l"
{ return AND_ASSIGN; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 91 "D:\\Testing\\Repos\\PythonGrammar\\PythonGrammar\\python_lexic.l"
{ return XOR_ASSIGN; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 92 "D:\\Testing\\Repos\\PythonGrammar\\PythonGrammar\\python_lexic.l"
{ return OR_ASSIGN; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 93 "D:\\Testing\\Repos\\PythonGrammar\\PythonGrammar\\python_lexic.l"
{ return RIGHT_OP; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 94 "D:\\Testing\\Repos\\PythonGrammar\\PythonGrammar\\python_lexic.l"
{ return LEFT_OP; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 95 "D:\\Testing\\Repos\\PythonGrammar\\PythonGrammar\\python_lexic.l"
{ return LE_OP; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 96 "D:\\Testing\\Repos\\PythonGrammar\\PythonGrammar\\python_lexic.l"
{ return GE_OP; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 97 "D:\\Testing\\Repos\\PythonGrammar\\PythonGrammar\\python_lexic.l"
{ return EQ_OP; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 98 "D:\\Testing\\Repos\\PythonGrammar\\PythonGrammar\\python_lexic.l"
{ return NE_OP; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 100 "D:\\Testing\\Repos\\PythonGrammar\\PythonGrammar\\python_lexic.l"
{ return ','; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 101 "D:\\Testing\\Repos\\PythonGrammar\\PythonGrammar\\python_lexic.l"
{ return ':'; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 102 "D:\\Testing\\Repos\\PythonGrammar\\PythonGrammar\\python_lexic.l"
{ return '='; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 103 "D:\\Testing\\Repos\\PythonGrammar\\PythonGrammar\\python_lexic.l"
{ return '('; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 104 "D:\\Testing\\Repos\\PythonGrammar\\PythonGrammar\\python_lexic.l"
{ return ')'; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 105 "D:\\Testing\\Repos\\PythonGrammar\\PythonGrammar\\python_lexic.l"
{ return '['; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 106 "D:\\Testing\\Repos\\PythonGrammar\\PythonGrammar\\python_lexic.l"
{ return ']'; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 107 "D:\\Testing\\Repos\\PythonGrammar\\PythonGrammar\\python_lexic.l"
{ return '{'; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 108 "D:\\Testing\\Repos\\PythonGrammar\\PythonGrammar\\python_lexic.l"
{ return '}'; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 109 "D:\\Testing\\Repos\\PythonGrammar\\PythonGrammar\\python_lexic.l"
{ return '.'; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 110 "D:\\Testing\\Repos\\PythonGrammar\\PythonGrammar\\python_lexic.l"
{ return '&'; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 111 "D:\\Testing\\Repos\\PythonGrammar\\PythonGrammar\\python_lexic.l"
{ return '@'; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 112 "D:\\Testing\\Repos\\PythonGrammar\\PythonGrammar\\python_lexic.l"
{ return '~'; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 113 "D:\\Testing\\Repos\\PythonGrammar\\PythonGrammar\\python_lexic.l"
{ return '-'; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 114 "D:\\Testing\\Repos\\PythonGrammar\\PythonGrammar\\python_lexic.l"
{ return '+'; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 115 "D:\\Testing\\Repos\\PythonGrammar\\PythonGrammar\\python_lexic.l"
{ return '%'; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 116 "D:\\Testing\\Repos\\PythonGrammar\\PythonGrammar\\python_lexic.l"
{ return '<'; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 117 "D:\\Testing\\Repos\\PythonGrammar\\PythonGrammar\\python_lexic.l"
{ return '>'; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 118 "D:\\Testing\\Repos\\PythonGrammar\\PythonGrammar\\python_lexic.l"
{ return '^'; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 119 "D:\\Testing\\Repos\\PythonGrammar\\PythonGrammar\\python_lexic.l"
{ return '|'; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 120 "D:\\Testing\\Repos\\PythonGrammar\\PythonGrammar\\python_lexic.l"
{ return '`'; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 121 "D:\\Testing\\Repos\\PythonGrammar\\PythonGrammar\\python_lexic.l"
{ return STAR; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 122 "D:\\Testing\\Repos\\PythonGrammar\\PythonGrammar\\python_lexic.l"
{ return DOUBLESTAR; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 123 "D:\\Testing\\Repos\\PythonGrammar\\PythonGrammar\\python_lexic.l"
{ return SLASH; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 124 "D:\\Testing\\Repos\\PythonGrammar\\PythonGrammar\\python_lexic.l"
{ return DOUBLESLASH; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 126 "D:\\Testing\\Repos\\PythonGrammar\\PythonGrammar\\python_lexic.l"
{
						printf("IDENTIFIER: %s\n", yytext);
						return IDENTIFIER;
					}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 131 "D:\\Testing\\Repos\\PythonGrammar\\PythonGrammar\\python_lexic.l"
{
						printf("DECINTEGER: %s\n", yytext);
						return DECINTEGER;
					}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 136 "D:\\Testing\\Repos\\PythonGrammar\\PythonGrammar\\python_lexic.l"
{
						printf("OCTINTEGER: %s\n", yytext);
						return OCTINTEGER;
					}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 141 "D:\\Testing\\Repos\\PythonGrammar\\PythonGrammar\\python_lexic.l"
{
						printf("HEXINTEGER: %s\n", yytext);
						return HEXINTEGER;
					}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 146 "D:\\Testing\\Repos\\PythonGrammar\\PythonGrammar\\python_lexic.l"
{
						printf("POINTFLOAT: %s\n", yytext);
						return POINTFLOAT;
					}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 151 "D:\\Testing\\Repos\\PythonGrammar\\PythonGrammar\\python_lexic.l"
{
						printf("EXPONENTFLOAT: %s\n", yytext);
						return EXPONENTFLOAT;
					}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 156 "D:\\Testing\\Repos\\PythonGrammar\\PythonGrammar\\python_lexic.l"
{
						printf("IMAGNUMBER: %s\n", yytext);
						return IMAGNUMBER;
					}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 162 "D:\\Testing\\Repos\\PythonGrammar\\PythonGrammar\\python_lexic.l"
{
						printf("SHORTSTRING: %s\n", yytext);
						return SHORTSTRING;
					}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 167 "D:\\Testing\\Repos\\PythonGrammar\\PythonGrammar\\python_lexic.l"
{
						printf("LONGSTRING: %s\n", yytext);
						return LONGSTRING;
					}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 172 "D:\\Testing\\Repos\\PythonGrammar\\PythonGrammar\\python_lexic.l"

	YY_BREAK
case 90:
YY_RULE_SETUP
#line 174 "D:\\Testing\\Repos\\PythonGrammar\\PythonGrammar\\python_lexic.l"
{
						line_number++;
						return NEWLINE;
					}
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 180 "D:\\Testing\\Repos\\PythonGrammar\\PythonGrammar\\python_lexic.l"
{ /* whitespace separates tokens */ }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 181 "D:\\Testing\\Repos\\PythonGrammar\\PythonGrammar\\python_lexic.l"
{ /* discard bad characters */ }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 183 "D:\\Testing\\Repos\\PythonGrammar\\PythonGrammar\\python_lexic.l"
ECHO;
	YY_BREAK
#line 1279 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 228 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 228 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 227);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 183 "D:\\Testing\\Repos\\PythonGrammar\\PythonGrammar\\python_lexic.l"


int yywrap(void) {
    return 1;
}

int yyerror(char *errmsg)
{
	printf("line %d: %s\n", line_number, errmsg);
	return 0;
}

int main(int argc, char**argv)
{
	if(argc < 2)
	{
		printf("Usage: %s <file>\n", argv[0]);
		exit(EXIT_FAILURE);
	}

	if(access(argv[1], 0))
	{
		printf("File doesn\'t exist!\n");
		exit(EXIT_FAILURE);
	}

	yyin = fopen(argv[1], "r");

	fseek(yyin, 0, SEEK_END);
	if(ftell(yyin) == 0)
	{
		printf("Input file is EMPTY!\n");
		exit(EXIT_FAILURE);
	}
	rewind(yyin);

	yyparse();
}